version: "3"

services: 
  elixir:
    image: elixir
    container_name: elixir
    restart: unless-stopped
    tty: true
    networks: 
      - rocketpay
    depends_on: 
    - postgres
    ports: 
      - 4000:4000
    volumes: 
      - ./rocketpay:/rocketpay
    working_dir: /rocketpay
  
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    networks: 
      - rocketpay
    ports: 
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres

volumes: 
  pgdata:

networks: 
  rocketpay: